name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:

    runs-on: ubuntu-latest

    concurrency:
      group: ci-dev-${{ github.ref }}
      cancel-in-progress: true

    env:
      COMPOSE_FILE: ci/docker-compose.yml
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          mamba-version: "*"
          environment-file: conda/dev.yaml
          channels: conda-forge,nodefaults
          activate-environment: poc-django
          use-mamba: true
          miniforge-variant: Mambaforge

      - name: Build djangopoc image
        run: make docker-build

      - name: start services
        run: |
          make docker-start

      - name: waiting for services
        run: |
          make docker-waiting

      - name: Run pre-commit check
        run: |
          pre-commit install
          pre-commit run --all-files
